config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :contacts
  resources :registers
  resources :ebooks
  resources :books
  resources :users

end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  before_action :set_ebook, only: [:show, :edit, :update, :destroy]

  # GET /ebooks
  # GET /ebooks.json
  def index
    @ebooks = Ebook.all
  end

  # GET /ebooks/1
  # GET /ebooks/1.json
  def show
  end

  # GET /ebooks/new
  def new
    @ebook = Ebook.new
  end

  # GET /ebooks/1/edit
  def edit
  end

  # POST /ebooks
  # POST /ebooks.json
  def create
    @ebook = Ebook.new(ebook_params)

    respond_to do |format|
      if @ebook.save
        format.html { redirect_to @ebook, notice: 'Ebook was successfully created.' }
        format.json { render :show, status: :created, location: @ebook }
      else
        format.html { render :new }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebooks/1
  # PATCH/PUT /ebooks/1.json
  def update
    respond_to do |format|
      if @ebook.update(ebook_params)
        format.html { redirect_to @ebook, notice: 'Ebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @ebook }
      else
        format.html { render :edit }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebooks/1
  # DELETE /ebooks/1.json
  def destroy
    @ebook.destroy
    respond_to do |format|
      format.html { redirect_to ebooks_url, notice: 'Ebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebook
      @ebook = Ebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ebook_params
      params.require(:ebook).permit(:name, :price, :author)
    end
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/views/ebooks/_form.html.erb
<%= form_for(@ebook) do |f| %>
  <% if @ebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ebook.errors.count, "error") %> prohibited this ebook from being saved:</h2>

      <ul>
      <% @ebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ebooks/edit.html.erb
<h1>Editing Ebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @ebook %> |
<%= link_to 'Back', ebooks_path %>

app/views/ebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ebooks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ebooks.each do |ebook| %>
      <tr>
        <td><%= ebook.name %></td>
        <td><%= ebook.price %></td>
        <td><%= ebook.author %></td>
        <td><%= link_to 'Show', ebook %></td>
        <td><%= link_to 'Edit', edit_ebook_path(ebook) %></td>
        <td><%= link_to 'Destroy', ebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ebook', new_ebook_path %>

app/views/ebooks/new.html.erb
<h1>New Ebook</h1>

<%= render 'form' %>

<%= link_to 'Back', ebooks_path %>

app/views/ebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ebook.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ebook.price %>
</p>

<p>
  <strong>Author:</strong>
  <%= @ebook.author %>
</p>

<%= link_to 'Edit', edit_ebook_path(@ebook) %> |
<%= link_to 'Back', ebooks_path %>